[package]
name = "squid-vm"
version = "0.7.4-alpha"
edition = "2021"
repository = "https://github.com/Fragmenta-Company/SquidVM"
authors = ["Nicolas Renan Machado Dias", "Fragmenta Company"]
description = "SquidVM is a VM made in Rust, having implemented a high performant architecture."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
devkit = []

[profile.release]
strip = "symbols"

[dependencies]
simple_logger = "4.3"
log = "0.4"
byteorder = "1.5"
arrayvec = { version = "0.7", features = [] }
fnv = { version = "1", features = [] }
clap = { version = "4", features = ["derive"] }
zip = "0.6"
