[package]
name = "squid-vm"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "4.3.0"
log = "0.4.20"
byteorder = "1.5.0"
arrayvec = { version = "0.7.4", features = [] }
