[package]
name = "squid-vm"
version = "0.4.2-alpha"
edition = "2021"
repository = "https://github.com/Fragmenta-Company/SquidVM"
authors = ["Nicolas Renan Machado Dias", "Fragmenta Company"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"

[dependencies]
simple_logger = "4.3.0"
log = "0.4.20"
byteorder = "1.5.0"
arrayvec = { version = "0.7.4", features = [] }
fnv = { version = "1.0.7", features = [] }
